"""empty message

Revision ID: 20c2fbb144f2
Revises: ee3900bd439f
Create Date: 2018-03-09 19:20:02.616117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c2fbb144f2'
down_revision = 'ee3900bd439f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('variant', sa.Integer(), nullable=True),
    sa.Column('q1_answer', sa.Integer(), nullable=True),
    sa.Column('q2_answer', sa.Integer(), nullable=True),
    sa.Column('q3_answer', sa.Integer(), nullable=True),
    sa.Column('q4_answer', sa.String(length=5000), nullable=True),
    sa.ForeignKeyConstraint(['q1_answer'], ['q1_answer.id'], ),
    sa.ForeignKeyConstraint(['q2_answer'], ['q2_answer.id'], ),
    sa.ForeignKeyConstraint(['q3_answer'], ['q3_answer.id'], ),
    sa.ForeignKeyConstraint(['variant'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_responses')
    # ### end Alembic commands ###
