"""empty message

Revision ID: 2b3149410897
Revises: 
Create Date: 2018-02-15 17:05:25.678655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3149410897'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('q1_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('q2_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('q3_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_name', sa.String(length=5000), nullable=True),
    sa.Column('igv_image', sa.String(length=50000), nullable=True),
    sa.Column('gEval_image', sa.String(length=50000), nullable=True),
    sa.Column('svviz_DotPlot_image', sa.String(length=50000), nullable=True),
    sa.Column('svviz_PB_image', sa.String(length=50000), nullable=True),
    sa.Column('svviz_Ill250_image', sa.String(length=50000), nullable=True),
    sa.Column('svviz_Ill300x_image', sa.String(length=50000), nullable=True),
    sa.Column('svviz_10X_image', sa.String(length=50000), nullable=True),
    sa.Column('svviz_MP_image', sa.String(length=50000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('variant', sa.Integer(), nullable=True),
    sa.Column('q1_answer', sa.Integer(), nullable=True),
    sa.Column('q2_answer', sa.Integer(), nullable=True),
    sa.Column('q3_answer', sa.Integer(), nullable=True),
    sa.Column('q4_answer', sa.String(length=5000), nullable=True),
    sa.ForeignKeyConstraint(['q1_answer'], ['q1_answer.id'], ),
    sa.ForeignKeyConstraint(['q2_answer'], ['q2_answer.id'], ),
    sa.ForeignKeyConstraint(['q3_answer'], ['q3_answer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_responses')
    op.drop_table('variants')
    op.drop_table('q3_answer')
    op.drop_table('q2_answer')
    op.drop_table('q1_answer')
    # ### end Alembic commands ###
