"""empty message

Revision ID: ee3900bd439f
Revises: 5c1e340fdd68
Create Date: 2018-03-09 19:16:04.695043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee3900bd439f'
down_revision = '5c1e340fdd68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_responses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_responses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user', sa.INTEGER(), nullable=True),
    sa.Column('variant', sa.INTEGER(), nullable=True),
    sa.Column('q1_answer', sa.INTEGER(), nullable=True),
    sa.Column('q2_answer', sa.INTEGER(), nullable=True),
    sa.Column('q3_answer', sa.INTEGER(), nullable=True),
    sa.Column('q4_answer', sa.VARCHAR(length=5000), nullable=True),
    sa.ForeignKeyConstraint(['q1_answer'], [u'q1_answer.id'], ),
    sa.ForeignKeyConstraint(['q2_answer'], [u'q2_answer.id'], ),
    sa.ForeignKeyConstraint(['q3_answer'], [u'q3_answer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
